// OSIS = Open Scripture Information Standard
export enum OsisToBookName {
  GEN = 'Genesis',
  EXO = 'Exodus',
  LEV = 'Leviticus',
  NUM = 'Numbers',
  DEU = 'Deuteronomy',
  JOS = 'Joshua',
  JDG = 'Judges',
  RUT = 'Ruth',
  '1SA' = '1 Samuel',
  '2SA' = '2 Samuel',
  '1KI' = '1 Kings',
  '2KI' = '2 Kings',
  '1CH' = '1 Chronicles',
  '2CH' = '2 Chronicles',
  EZR = 'Ezra',
  NEH = 'Nehemiah',
  EST = 'Esther',
  JOB = 'Job',
  PSA = 'Psalms',
  PRO = 'Proverbs',
  ECC = 'Ecclesiastes',
  SNG = 'Song of Solomon',
  ISA = 'Isaiah',
  JER = 'Jeremiah',
  LAM = 'Lamentations',
  EZK = 'Ezekiel',
  DAN = 'Daniel',
  HOS = 'Hosea',
  JOL = 'Joel',
  AMO = 'Amos',
  OBA = 'Obadiah',
  JON = 'Jonah',
  MIC = 'Micah',
  NAM = 'Nahum',
  HAB = 'Habakkuk',
  ZEP = 'Zephaniah',
  HAG = 'Haggai',
  ZEC = 'Zechariah',
  MAL = 'Malachi',
  MAT = 'Matthew',
  MRK = 'Mark',
  LUK = 'Luke',
  JHN = 'John',
  ACT = 'Acts',
  ROM = 'Romans',
  '1CO' = '1 Corinthians',
  '2CO' = '2 Corinthians',
  GAL = 'Galatians',
  EPH = 'Ephesians',
  PHP = 'Philippians',
  COL = 'Colossians',
  '1TH' = '1 Thessalonians',
  '2TH' = '2 Thessalonians',
  '1TI' = '1 Timothy',
  '2TI' = '2 Timothy',
  TIT = 'Titus',
  PHM = 'Philemon',
  HEB = 'Hebrews',
  JAS = 'James',
  '1PE' = '1 Peter',
  '2PE' = '2 Peter',
  '1JN' = '1 John',
  '2JN' = '2 John',
  '3JN' = '3 John',
  JUD = 'Jude',
  REV = 'Revelation',
}

export enum BookNameToOsis {
  Genesis = 'GEN',
  Exodus = 'EXO',
  Leviticus = 'LEV',
  Numbers = 'NUM',
  Deuteronomy = 'DEU',
  Joshua = 'JOS',
  Judges = 'JDG',
  Ruth = 'RUT',
  '1 Samuel' = '1SA',
  '2 Samuel' = '2SA',
  '1 Kings' = '1KI',
  '2 Kings' = '2KI',
  '1 Chronicles' = '1CH',
  '2 Chronicles' = '2CH',
  Ezra = 'EZR',
  Nehemiah = 'NEH',
  Esther = 'EST',
  Job = 'JOB',
  Psalms = 'PSA',
  Proverbs = 'PRO',
  Ecclesiastes = 'ECC',
  'Song of Solomon' = 'SNG',
  Isaiah = 'ISA',
  Jeremiah = 'JER',
  Lamentations = 'LAM',
  Ezekiel = 'EZK',
  Daniel = 'DAN',
  Hosea = 'HOS',
  Joel = 'JOL',
  Amos = 'AMO',
  Obadiah = 'OBA',
  Jonah = 'JON',
  Micah = 'MIC',
  Nahum = 'NAM',
  Habakkuk = 'HAB',
  Zephaniah = 'ZEP',
  Haggai = 'HAG',
  Zechariah = 'ZEC',
  Malachi = 'MAL',
  Matthew = 'MAT',
  Mark = 'MRK',
  Luke = 'LUK',
  John = 'JHN',
  Acts = 'ACT',
  Romans = 'ROM',
  '1 Corinthians' = '1CO',
  '2 Corinthians' = '2CO',
  Galatians = 'GAL',
  Ephesians = 'EPH',
  Philippians = 'PHP',
  Colossians = 'COL',
  '1 Thessalonians' = '1TH',
  '2 Thessalonians' = '2TH',
  '1 Timothy' = '1TI',
  '2 Timothy' = '2TI',
  Titus = 'TIT',
  Philemon = 'PHM',
  Hebrews = 'HEB',
  James = 'JAS',
  '1 Peter' = '1PE',
  '2 Peter' = '2PE',
  '1 John' = '1JN',
  '2 John' = '2JN',
  '3 John' = '3JN',
  Jude = 'JUD',
  Revelation = 'REV',
}

export const COMMON_NAME_OSIS_MAP: Map<string, string> = new Map([
  ['gen', 'GEN'],
  ['genesis', 'GEN'],
  ['exo', 'EXO'],
  ['exod', 'EXO'],
  ['exodus', 'EXO'],
  ['lev', 'LEV'],
  ['leviticus', 'LEV'],
  ['num', 'NUM'],
  ['numbers', 'NUM'],
  ['deu', 'DEU'],
  ['deut', 'DEU'],
  ['deuteronomy', 'DEU'],
  ['jos', 'JOS'],
  ['josh', 'JOS'],
  ['joshua', 'JOS'],
  ['jdg', 'JDG'],
  ['judg', 'JDG'],
  ['judges', 'JDG'],
  ['rut', 'RUT'],
  ['ruth', 'RUT'],
  ['1sa', '1SA'],
  ['1samuel', '1SA'],
  ['2sa', '2SA'],
  ['2samuel', '2SA'],
  ['1ki', '1KI'],
  ['1kgs', '1KI'],
  ['1kings', '1KI'],
  ['2ki', '2KI'],
  ['2kgs', '2KI'],
  ['2kings', '2KI'],
  ['1ch', '1CH'],
  ['1chr', '1CH'],
  ['1chronicles', '1CH'],
  ['chronicles1', '1CH'],
  ['2ch', '2CH'],
  ['2chr', '2CH'],
  ['2chronicles', '2CH'],
  ['chronicles2', '2CH'],
  ['ezr', 'EZR'],
  ['ezra', 'EZR'],
  ['neh', 'NEH'],
  ['nehemiah', 'NEH'],
  ['est', 'EST'],
  ['esth', 'EST'],
  ['ester', 'EST'],
  ['job', 'JOB'],
  ['ps', 'PSA'],
  ['psa', 'PSA'],
  ['psalms', 'PSA'],
  ['psalm', 'PSA'],
  ['pro', 'PRO'],
  ['prov', 'PRO'],
  ['proverbs', 'PRO'],
  ['ecc', 'ECC'],
  ['eccl', 'ECC'],
  ['ecclesiastes', 'ECC'],
  ['sng', 'SNG'],
  ['song', 'SNG'],
  ['songofsolomon', 'SNG'],
  ['isa', 'ISA'],
  ['isaiah', 'ISA'],
  ['jer', 'JER'],
  ['jeremiah', 'JER'],
  ['lam', 'LAM'],
  ['lamentations', 'LAM'],
  ['ezk', 'EZK'],
  ['ezek', 'EZK'],
  ['ezekiel', 'EZK'],
  ['dan', 'DAN'],
  ['daniel', 'DAN'],
  ['hos', 'HOS'],
  ['hosea', 'HOS'],
  ['jol', 'JOL'],
  ['joel', 'JOL'],
  ['amo', 'AMO'],
  ['amos', 'AMO'],
  ['oba', 'OBA'],
  ['obad', 'OBA'],
  ['obadiah', 'OBA'],
  ['jon', 'JON'],
  ['jonah', 'JON'],
  ['mic', 'MIC'],
  ['micah', 'MIC'],
  ['nam', 'NAM'],
  ['nah', 'NAM'],
  ['nahum', 'NAM'],
  ['hab', 'HAB'],
  ['habakkuk', 'HAB'],
  ['zep', 'ZEP'],
  ['zeph', 'ZEP'],
  ['zepaniah', 'ZEP'],
  ['hag', 'HAG'],
  ['haggai', 'HAG'],
  ['zec', 'ZEC'],
  ['zech', 'ZEC'],
  ['zechariah', 'ZEC'],
  ['mal', 'MAL'],
  ['malachi', 'MAL'],
  ['mat', 'MAT'],
  ['matt', 'MAT'],
  ['matthew', 'MAT'],
  ['mrk', 'MRK'],
  ['mark', 'MRK'],
  ['luk', 'LUK'],
  ['luke', 'LUK'],
  ['jhn', 'JHN'],
  ['john', 'JHN'],
  ['act', 'ACT'],
  ['acts', 'ACT'],
  ['rom', 'ROM'],
  ['romans', 'ROM'],
  ['1co', '1CO'],
  ['1cor', '1CO'],
  ['1corinthians', '1CO'],
  ['2co', '2CO'],
  ['2cor', '2CO'],
  ['2corinthians', '2CO'],
  ['gal', 'GAL'],
  ['galatians', 'GAL'],
  ['eph', 'EPH'],
  ['ephesians', 'EPH'],
  ['php', 'PHP'],
  ['phil', 'PHP'],
  ['philippians', 'PHP'],
  ['col', 'COL'],
  ['colossians', 'COL'],
  ['1th', '1TH'],
  ['1thess', '1TH'],
  ['1thessalonians', '1TH'],
  ['2th', '2TH'],
  ['2thess', '2TH'],
  ['2thessalonians', '2TH'],
  ['1ti', '1TI'],
  ['1tim', '1TI'],
  ['1timothy', '1TI'],
  ['2ti', '2TI'],
  ['2tim', '2TI'],
  ['2timothy', '2TI'],
  ['tit', 'TIT'],
  ['titus', 'TIT'],
  ['phm', 'PHM'],
  ['phlm', 'PHM'],
  ['philemon', 'PHM'],
  ['heb', 'HEB'],
  ['hebrews', 'HEB'],
  ['jas', 'JAS'],
  ['james', 'JAS'],
  ['1pe', '1PE'],
  ['1pet', '1PE'],
  ['1peter', '1PE'],
  ['2pe', '2PE'],
  ['2pet', '2PE'],
  ['2peter', '2PE'],
  ['1jn', '1JN'],
  ['1john', '1JN'],
  ['2jn', '2JN'],
  ['2john', '2JN'],
  ['3jn', '3JN'],
  ['3john', '3JN'],
  ['jud', 'JUD'],
  ['jude', 'JUD'],
  ['rev', 'REV'],
  ['revelation', 'REV'],
]);
